services:
  # Databases
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: mealprep
      POSTGRES_USER: mealprep
      POSTGRES_PASSWORD: mealprep_secure_2024
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
    ports:
      - "35432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mealprep"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "36379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  # Core Services
  api-gateway:
    build:
      context: ./services/api-gateway
      dockerfile: Dockerfile
    ports:
      - "38080:8080"
    environment:
      - RUST_LOG=debug
      - DATABASE_URL=postgresql://mealprep:mealprep_secure_2024@postgres:5432/mealprep
      - REDIS_URL=redis://redis:6379
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    restart: unless-stopped

  nutrition-service:
    build:
      context: ./services/nutrition-service
      dockerfile: Dockerfile
    environment:
      - RUST_LOG=debug
      - DATABASE_URL=postgresql://mealprep:mealprep_secure_2024@postgres:5432/mealprep
      - REDIS_URL=redis://redis:6379
      - AI_MODEL_PATH=/app/models
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    restart: unless-stopped

  analytics-service:
    build:
      context: ./services/analytics-service
      dockerfile: Dockerfile
    environment:
      - RUST_LOG=debug
      - DATABASE_URL=postgresql://mealprep:mealprep_secure_2024@postgres:5432/mealprep
      - REDIS_URL=redis://redis:6379
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    restart: unless-stopped

  # Frontend
  web-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "39000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:38080/api
      - REACT_APP_WS_URL=ws://localhost:38080/ws
    depends_on:
      - api-gateway
    restart: unless-stopped

  # Monitoring
  prometheus:
    image: prom/prometheus:latest
    container_name: meal_prep_3-prometheus-1
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    networks:
      - default

  grafana:
    image: grafana/grafana:latest
    ports:
      - "39091:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin123
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana:/etc/grafana/provisioning
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
  prometheus_data:
  grafana_data:

networks:
  default:
    driver: bridge
